name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        # Exposing the github temp dir to node.js so it can be picked
        # up in our tests by os.tmpdir()
        # https://github.com/nodejs/node/blob/def014dff3b183902599a36bed056e6811e067cf/lib/os.js#L191
        # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
        env:
          TMPDIR: "$RUNNER_TEMP"
